server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]::443 quic;
    
    server_name a.example.com;
    
    # 证书配置
    ssl_certificate         /etc/letsencrypt/live/a.example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/a.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/a.example.com/chain.pem;
    
    # 如果使用 CDN，可以开启 mTLS，限定 CDN 节点才能访问源站
    ssl_client_certificate  /etc/nginx/certs/cdn.crt; # 客户端证书
    ssl_verify_client       on;
    ssl_verify_depth        2;

    # 客户端证书错误，直接关闭连接，防止 Nginx 返回错误页面提示非法访问者
    error_page 495 496 = @wrong_client_cert;
    location @wrong_client_cert {
        return 444;
    }
    
    add_header Alt-Svc 'h3=":443"; ma=86400' always; # 告诉客户端可以使用 HTTP/3
    add_header X-Frame-Options "SAMEORIGIN" always; # 只有同域名的页面才能使用 iframe 嵌入
    add_header X-Content-Type-Options "nosniff"; # 让客户端遵循 Content-Type 的设定
    add_header Referrer-Policy "strict-origin-when-cross-origin" always; # 对于同源的请求，发送来源、路径以及查询字符串。对于在相同安全级别的情况下（HTTPS→HTTPS）的跨源请求，仅发送来源。在目标的安全级别下降的情况下（HTTPS→HTTP）则不发送 Referer 标头。
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; # 告诉客户端接下来一年访问本站所有域名都使用 HTTPS

    absolute_redirect off; # 301 等跳转时，Location 使用网站相对路径。在某些 CDN 场景下，用户访问的域名和 CDN 回源的域名不一样，使用这条配置可以防止用户跳转到源站域名
    
    root /var/www/a; # 网站根目录
    index index.html; # 访问目录时，寻找目录下的 index.html 并返回
    error_page 404 /404.html; # 如果返回 404，内部跳转到 /404.html 并返回其内容
    
    location = /404.html {
        internal; # 限制这个地址只能被内部访问，防止外部访问返回 200
    }
    
    location ~ /index\.html$ {
        internal; # 限制外部访问，防止出现两个内容一样但链接不同的页面
        add_header Cache-Control "no-cache";
    }

    location /img/ {
        # 前缀替换
        alias /srv/img/;
    }

    # 反向代理服务器
    location /_AMapService/ {
        set $args "$args&jscode=xxx";
        # 目标服务器结尾有 /，此时 proxy_pass 的工作方式类似于 alias，把当前 URL 前缀后面的内容拼接到服务器地址后面
        proxy_pass https://restapi.amap.com/;
    }

    # 也是作为反向代理服务器
    location /api/ {
        # 目标服务器结尾没有 /，此时 proxy_pass 的工作方式类似于 root，把当前整个 URL 地址传给服务器
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 默认 location
    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ =404; # 先尝试查找 uri 对应的文件，没有就尝试有没有该目录（是目录的话内部跳转到相应的 index.html），否则返回 404
    }
}
